- name: install python3 on all instances
  hosts: "*"
  gather_facts: false
  tasks:
    - name: run as root - yum update, yum install python, node, pm2, ping ..., touch file
      raw: "{{ item }}"
      loop:
        - touch /root/ansible-yum-update
        - sudo yum update
        - touch /root/ansible-yum-install-py
        - sudo yum install python
        #- touch ansible-run-bash-profile
        #- . ./.bash_profile
        #- echo "$PATH"
        #- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
        #- . ~/.nvm/nvm.sh
        #- touch ansible-install-nvm
        #- bash -c '. ~/.nvm/nvm.sh; nvm install '
        #- bash -c '. /home/ec2-user/.nvm/nvm.sh; nvm install '
        #- touch ansible-run-nvm-sh
        #- touch ansible-install-node
        #- nvm install node
        #- touch ansible-install-pm2
        #- npm install pm2 -g
        #- touch ansible-run-pm2-npm-start
        #- pm2 "npm start"
        #- touch ansible-ping
        #- ping -c 3 8.8.8.8
        #- touch ansible-finish
      become: true
      #become: yes
      become_user: root
      #ignore_errors: true
    - debug: var=ansible_host
    #
    - name: Run as ec2-user
      raw: "{{ item }}"
      loop:
        #- bash -c 'touch ansible-install-node-using-nvm'
        #- bash -c '. ~ec2-user/.nvm/nvm.sh; nvm install '
        #- bash -c 'nvm install node'
        - bash -c 'touch ~ec2-user/ansible-install-pm2'
        - bash -c 'npm install pm2 -g'
        - bash -c 'touch ~ec2-user/ansible-run-pm2-npm-start'
        - bash -c 'pm2 "npm start"'
        - bash -c 'pm2 list'
        - bash -c 'touch ~ec2-user/ansible-ping'
        - bash -c 'ping -c 3 8.8.8.8'
        - bash -c 'touch ~ec2-user/ansible-finish'
      become: true
      #become: yes
      become_user: ec2-user
