- name: install python2 on AWS RedHat instances
  hosts: "*"
  gather_facts: false
  tasks:
    - name: run yum update and install python
      raw: "{{ item }}"
      loop:
        - sudo yum update
        - sudo yum install python
      become: true

- name: misc task on AWS RedHat instance
  hosts: "*"
  tasks:
    - debug: var=ansible_host


