---
#
# https://docs.ansible.com/ansible/latest/modules/copy_module.html#examples
# https://www.decodingdevops.com/ansible-copy-module/
#
# Ansible Copy
# https://www.javatpoint.com/ansible-copy
#
# Run:
# $ ansible-playbook playb_cp2s3.yml
#
#     "aws s3 sync dist/ s3://s3-uda-deploy --acl public-read"
#
- hosts: "aws_ubuntu"
  tasks:  
  - name: Ansible copy frontend files to s3 bucket
    copy:
      src: frontend/dist/
      dest: s3://s3-uda-deploy
      # force: yes

  #
  #- name: Ansible copy 'ecosystem.config.js' file to a remote server  
  #  copy:
  #    src: ecosystem.config.js
  #    dest: ~/uda-deploy/
  #    # force: yes
