# Run:
# cdond-c3-projectstarter $ ansible-playbook playb_upgrade.yml
#
- name: Install python3 on all instances and make maintenance
  hosts: "*"
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - debug: var=ansible_host
    - name: run as root - yum update, yum install python, node, pm2 ...
      #ignore_errors: true
      raw: "{{ item }}"
      loop:
        - touch /root/ansible-yum-update
        - sudo yum update
        - touch /root/ansible-yum-install-py
        - sudo yum install python
