---
#
# https://docs.ansible.com/ansible/latest/modules/copy_module.html#examples
# https://www.decodingdevops.com/ansible-copy-module/
#
# Ansible Copy
# https://www.javatpoint.com/ansible-copy
#
# Run:
# $ ansible-playbook playb_cp_file.yml
#
- hosts: "*"
  tasks:  
  - name: Ansible copy file to a remote server  
    copy:
      src: README.md
      dest: README.md
