# https://www.bogotobogo.com/DevOps/Ansible/Ansible-SSH-Connection-Setup-Run-Command.php
# hosts file
# 34.204.95.58
---
[dev]
ec2-34-204-95-58.compute-1.amazonaws.com
[dev:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/pedro/.ssh/id_rsa

