---
#
# https://docs.ansible.com/ansible/latest/modules/copy_module.html#examples
# https://www.decodingdevops.com/ansible-copy-module/
#
# Ansible Copy
# https://www.javatpoint.com/ansible-copy
#
# Run:
# cdond-c3-projectstarter $ ansible-playbook playb_cp_file_env.yml
#
- hosts: "*"
  tasks:  
  - name: Ansible copy file to a remote server  
    copy:
      src: backend/.env
      dest: ~/uda-deploy/backend/.env
      force: yes
