# nvm_user: the user with .nvm install
# https://truongtx.me/2015/11/02/ansible-install-and-work-with-nodejs-using-nvm

- name: install nodejs using nvm
  sudo: yes
  sudo_user: ""
  command: bash -c '. ~/.nvm/nvm.sh; nvm install '

- name: set default node version
  sudo: yes
  sudo_user: ""
  command: bash -c '. ~/.nvm/nvm.sh; nvm alias default '
 