Description: >
  UdaPeople frontend stack.
  Create an S3 Bucket that hosts a site.

Parameters:
  ID:
    Description: Unique identifier. This will be in the S3 URL.
    Type: String

Resources:
  # Create an S3 Bucket that serves a static website (i.e. React app)
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "udapeople-${ID}"
      AccessControl: PublicRead   # Visitors need to be able to access the site
      WebsiteConfiguration:       # This makes the S3 Bucket a static website/app
        IndexDocument: index.html  # Default object served when visiting S3 domain
        ErrorDocument: 404.html    # Error page NOT FOUND
  
  # Add a Bucket Policy that lets public visitors access the web app
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'  # Attach to bucket ('WebsiteBucket') being created
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'       # Wildcard '*', allow all requests
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL for website hosted on S3
