#
version: 2.1

#jobs:
#  hello-world:
#    docker:
#      - image: amazon/aws-cli
#    steps:
#      - checkout
#      - run:
#          name: Say Hello
#          command: |
#            echo "Hello World"
#
#workflows:
#  default:
#    jobs:
#      - hello-world
#
# https://circleci.com/docs/2.0/getting-started/#section=getting-started
#version: 2.1
# https://circleci.com/docs/2.0/circleci-images/
#- image: circleci/postgres:[TAG]
#
#orbs:
#  node: circleci/node@1.1
#
#jobs:
#  build:
#    executor:
#      name: node/default
#      tag: '10.4'
#    steps:
#      - checkout
#      - node/with-cache:
#          steps:
#            - run: npm install
#      - run: npm run test
##
#workflows:
#  default:
#    jobs:
#      - build
#
# https://circleci.com/docs/2.0/hello-world/
#
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
