version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: cd folder/dir frontend, ls -las
          command: |
            cd frontend && ls -als
      - run:
          name: List folder/dir where we are
          command: |
            ls -las
      - run:
          name: cd frontend and run lint
          command: |
            cd frontend; npm run lint
      - run:
          name: Say Hello to Udapeople
          command: |
            echo "Udapeople: Hello World"

workflows:
  default:
    jobs:
      - hello-world
