version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: cd folder/dir
          command: |
            cd frontend
      - run:
          name: List folder/dir
          command: |
            ls -las
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

workflows:
  default:
    jobs:
      - hello-world
