orbs:
  node: circleci/node@2.0.2

version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "uda-deploy: Hello World"

workflows:
  matrix-tests:
    jobs:
      - node/test:
          app-dir: frontend
          version: 10.15.2
      - node/test:
          app-dir: backend
          version: 10.15.2
      - hello-world

