version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello to Udapeople
          command: |
            echo "Udapeople: Hello World"

  lint:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: cd folder/dir frontend, ls -las
          command: |
            cd frontend && ls -als
      - run:
          name: List folder/dir where we are
          command: |
            ls -las
      - run:
          name: cd frontend, install 'npm i' and and run lint
          command: |
            cd frontend; npm install ; npm run lint


workflows:
  default:
    jobs:
      - lint
      - hello-world

