version: 2.1

orbs:
  node: circleci/node@1.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "uda-deploy: Hello World"
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test


workflows:
  default:
    jobs:
      - hello-world
      - build
          app-dir: backend
