version: 2.1

jobs:
  hello-world-udapeople:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello to Udapeople
          command: |
            echo "Udapeople: Hello World"

  lint-frontend:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: cd folder/dir frontend, ls -las
          command: |
            cd frontend && ls -als
      - run:
          name: List folder/dir where we are
          command: |
            ls -las
      - run:
          name: cd frontend, install 'npm i' and run lint
          command: |
            cd frontend; npm install ; npm run lint

  lint-backend:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: cd folder/dir backend, ls -las
          command: |
            cd backend && ls -als
      - run:
          name: List folder/dir where we are
          command: |
            ls -las
      - run:
          name: cd backend, install 'npm i' and run lint
          command: |
            cd backend; npm install ; npm run lint

  run-frontend:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: cd folder/dir frontend, ls -las
          command: |
            cd frontend && ls -als
      - run:
          name: List folder/dir where we are
          command: |
            ls -las
      - run:
          name: cd frontend, install 'npm i'
          command: |
            cd frontend; npm install 
      - run:
          name: cd frontend,  and run 'npm audit'
          command: |
            cd frontend; npm audit --audit-level=critical
      - run:
          name: cd frontend, and run 'npm start'
          command: |
            cd frontend; npm run start

  run-backend:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: cd folder/dir backend, ls -las
          command: |
            cd backend && ls -als
      - run:
          name: List folder/dir where we are
          command: |
            ls -las
      - run:
          name: cd backend, install 'npm i'
          command: |
            cd backend; npm install
      - run:
          name: cd backend,  run 'npm audit'
          command: |
            cd backend; npm audit --audit-level=critical
      - run:
          name: cd backend, run 'npm start'
          command: |
            cd backend;  npm run start


workflows:
  default:
    jobs:
      #- lint-frontend
      #- lint-backend
      - run-frontend
      - run-backend
      - hello-world-udapeople
