---

# https://circleci.com/orbs/registry/orb/frameio/cloudformation
# Commands: deploy, lint
#

orbs:
  cloudformation: frameio/cloudformation@0.15.0
version: 2.1

workflows:
  deploy:
    jobs:
      - cloudformation/deploy:
          template: .circleci/files/frontend.yml
          stack_name: mystack
